language: cpp

compiler: clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

sudo: required
dist: trusty

env:
  global:
    - LLVM_VERSION=3.7.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
    - COMPILER=clang++-3.7

before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH

install:
  - clang++ --version

script:
  - mkdir ../ukf_build
  - cd ../ukf_build
  - cmake ../ukf
  - make unittest
  - test/unittest
